# Generated by Django 3.0.3 on 2020-02-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.IntegerField(verbose_name='Team Code')),
                ('team_name', models.CharField(blank=True, max_length=20, verbose_name='Team Name')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session', verbose_name="User's Session")),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Team', verbose_name="User's Team")),
            ],
        ),
    ]
