# Generated by Django 3.0.3 on 2020-02-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_team_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session',
            field=models.CharField(default='fakesession', max_length=40, verbose_name='Session ID'),
            preserve_default=False,
        ),
    ]
